package com.self.gs.string;
/*
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class FindDiff {
	
  public static void main(String[] args) {
	System.err.println(diff("abcdeg","abcde"));
}

private static char diff(String s, String t) {
	 int charCodeS = 0;
	 int charCodeT = 0;
	 for(char c:s.toCharArray()) {
		 charCodeS += c;
	 }
	 for(char c:t.toCharArray()) {
		 charCodeT += c;
	 }
	 
	 return (char)(Math.abs(charCodeS-charCodeT));
}
}
