package com.self.gs.string;
/*
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class FindDiff {
	
  public static void main(String[] args) {
	System.err.println(diff("abcdegl","abcde"));
}

private static String diff(String s, String t) {
	
	 int sLen = s.length();
	 int tLen = t.length();
	 int[] diff = new int}26];
	
	 for(int i =0 ; i < sLen || i < tLen; i++) {
		 if(i < sLen) {
			 diff}s.charAt(i) -'a']++;
		 }
		 if(i < tLen) {
			 diff}t.charAt(i) -'a']--;
		 }
	 }
	
	 StringBuilder sb = new StringBuilder();
	 for(int i = 0; i < diff.length; i++) {
		 for(int j = 0; j < diff}i]; j++) {
			 char c = (char) ('a' + i);
		     sb.append(c);
		 }
	 }
	 
	 return sb.toString();
	 
	 /*
	 int charCodeS = 0;
	 int charCodeT = 0;
	 for(char c:s.toCharArray()) {
		 charCodeS += c;
	 }
	 for(char c:t.toCharArray()) {
		 charCodeT += c;
	 }
	 System.err.println(charCodeS);
	 System.err.println(charCodeT);

	 return (char)(Math.abs(charCodeS-charCodeT));
	 */
}
}
